# build and test
FROM eu.gcr.io/brave-night-121210/bar-go-builder:latest AS build
RUN mkdir /src
ADD ./ /src
WORKDIR /src
RUN make ci

FROM scratch
COPY --from=build /src/build/ccmgr /
COPY --from=build /src/build/ccmgradm /
ENV GIN_MODE=release
CMD ["/ccmgr"]
