ARG BUILD_NUMBER

# build and test
FROM eu.gcr.io/brave-night-121210/bar-go-builder:latest AS build
RUN mkdir /src
ADD ./ /src
WORKDIR /src
RUN make ci

# get frontend files
FROM eu.gcr.io/brave-night-121210/clustercontrol-manager-frontend:build-$BUILD_NUMBER AS fe

FROM scratch
COPY --from=build /src/build/ccmgr /
COPY --from=build /src/build/ccmgradm /
COPY --from=fe /app /app
ENV GIN_MODE=release
CMD ["/ccmgr","--basedir=/data"]
